[2020-01-20 18:35:17,762] [INFO] [42e9e102-bf08-4f83-99b0-e65bff1d8084] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] before_request: 87 : Request-Start] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 18:35:18,597] [ERROR] [42e9e102-bf08-4f83-99b0-e65bff1d8084] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/common/utils.py] log_exception: 159 : Got exception during processing: ] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 49, in initialize
    self.message.mail.login(current_app.config['USER'], current_app.config['PASSWORD'])
  File "/usr/lib/python3.7/imaplib.py", line 598, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/apis/email_parser.py", line 18, in get
    ExtractDataFromXlsxFileService)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 18, in __init__
    self.initialize()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 55, in initialize
    raise InvalidEmailData
app.common.exceptions.InvalidEmailData
[2020-01-20 18:35:18,606] [ERROR] [42e9e102-bf08-4f83-99b0-e65bff1d8084] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/common/utils.py] log_exception: 159 : Got exception during processing: ] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 49, in initialize
    self.message.mail.login(current_app.config['USER'], current_app.config['PASSWORD'])
  File "/usr/lib/python3.7/imaplib.py", line 598, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/apis/email_parser.py", line 18, in get
    ExtractDataFromXlsxFileService)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 18, in __init__
    self.initialize()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 55, in initialize
    raise InvalidEmailData
app.common.exceptions.InvalidEmailData
[2020-01-20 18:35:18,609] [ERROR] [42e9e102-bf08-4f83-99b0-e65bff1d8084] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/common/utils.py] log_exception: 159 : Got exception during processing: ] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 49, in initialize
    self.message.mail.login(current_app.config['USER'], current_app.config['PASSWORD'])
  File "/usr/lib/python3.7/imaplib.py", line 598, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/apis/email_parser.py", line 18, in get
    ExtractDataFromXlsxFileService)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 18, in __init__
    self.initialize()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 55, in initialize
    raise InvalidEmailData
app.common.exceptions.InvalidEmailData
[2020-01-20 18:39:35,114] [INFO] [91212edc-5b28-4851-9fb7-fc7d132f214f] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] before_request: 87 : Request-Start] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 18:39:36,010] [ERROR] [91212edc-5b28-4851-9fb7-fc7d132f214f] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/common/utils.py] log_exception: 159 : Got exception during processing: ] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 50, in initialize
    self.message.mail.login(current_app.config['USER'], current_app.config['PASSWORD'])
  File "/usr/lib/python3.7/imaplib.py", line 598, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/apis/email_parser.py", line 18, in get
    ExtractDataFromXlsxFileService)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 19, in __init__
    self.initialize()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 55, in initialize
    raise InvalidEmailData
app.common.exceptions.InvalidEmailData
[2020-01-20 18:39:36,032] [ERROR] [91212edc-5b28-4851-9fb7-fc7d132f214f] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/common/utils.py] log_exception: 159 : Got exception during processing: ] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 50, in initialize
    self.message.mail.login(current_app.config['USER'], current_app.config['PASSWORD'])
  File "/usr/lib/python3.7/imaplib.py", line 598, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/apis/email_parser.py", line 18, in get
    ExtractDataFromXlsxFileService)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 19, in __init__
    self.initialize()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 55, in initialize
    raise InvalidEmailData
app.common.exceptions.InvalidEmailData
[2020-01-20 18:39:36,034] [ERROR] [91212edc-5b28-4851-9fb7-fc7d132f214f] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/common/utils.py] log_exception: 159 : Got exception during processing: ] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 50, in initialize
    self.message.mail.login(current_app.config['USER'], current_app.config['PASSWORD'])
  File "/usr/lib/python3.7/imaplib.py", line 598, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/apis/email_parser.py", line 18, in get
    ExtractDataFromXlsxFileService)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 19, in __init__
    self.initialize()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 55, in initialize
    raise InvalidEmailData
app.common.exceptions.InvalidEmailData
[2020-01-20 18:40:40,281] [INFO] [6a4e8874-b229-4a16-8afa-cea8fc4aa252] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] before_request: 87 : Request-Start] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 18:40:49,731] [ERROR] [6a4e8874-b229-4a16-8afa-cea8fc4aa252] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/common/utils.py] log_exception: 159 : Got exception during processing: (1364, "Field 'id' doesn't have a default value")] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/apis/email_parser.py", line 19, in get
    service.read_emails()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 25, in read_emails
    self.fetch_emails()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 78, in fetch_emails
    self.insert_eids()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 69, in insert_eids
    insert_many_eid(conn, self.message)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/models/mysql/email_parser.py", line 24, in insert_many_eid
    insert_rows(conn, params=params, sql_stmt=sql_scripts['insert_into_eid'])
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/models/mysql/helper.py", line 18, in insert_rows
    cursor.executemany(sql_stmt, params)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/cursors.py", line 197, in executemany
    self._get_db().encoding)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/cursors.py", line 234, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1364, "Field 'id' doesn't have a default value")
[2020-01-20 18:40:49,738] [ERROR] [6a4e8874-b229-4a16-8afa-cea8fc4aa252] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/common/utils.py] log_exception: 159 : Got exception during processing: (1364, "Field 'id' doesn't have a default value")] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/apis/email_parser.py", line 19, in get
    service.read_emails()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 25, in read_emails
    self.fetch_emails()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 78, in fetch_emails
    self.insert_eids()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 69, in insert_eids
    insert_many_eid(conn, self.message)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/models/mysql/email_parser.py", line 24, in insert_many_eid
    insert_rows(conn, params=params, sql_stmt=sql_scripts['insert_into_eid'])
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/models/mysql/helper.py", line 18, in insert_rows
    cursor.executemany(sql_stmt, params)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/cursors.py", line 197, in executemany
    self._get_db().encoding)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/cursors.py", line 234, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1364, "Field 'id' doesn't have a default value")
[2020-01-20 18:40:49,739] [ERROR] [6a4e8874-b229-4a16-8afa-cea8fc4aa252] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/common/utils.py] log_exception: 159 : Got exception during processing: (1364, "Field 'id' doesn't have a default value")] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/apis/email_parser.py", line 19, in get
    service.read_emails()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 25, in read_emails
    self.fetch_emails()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 78, in fetch_emails
    self.insert_eids()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 69, in insert_eids
    insert_many_eid(conn, self.message)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/models/mysql/email_parser.py", line 24, in insert_many_eid
    insert_rows(conn, params=params, sql_stmt=sql_scripts['insert_into_eid'])
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/models/mysql/helper.py", line 18, in insert_rows
    cursor.executemany(sql_stmt, params)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/cursors.py", line 197, in executemany
    self._get_db().encoding)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/cursors.py", line 234, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1364, "Field 'id' doesn't have a default value")
[2020-01-20 18:42:28,208] [INFO] [27f20a0b-212b-40b8-a67f-ee28ad462bec] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] before_request: 87 : Request-Start] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 18:42:36,398] [INFO] [27f20a0b-212b-40b8-a67f-ee28ad462bec] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] teardown_request: 91 : Request-End] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 18:43:05,528] [INFO] [6d0abcd8-0b1c-4ec5-a165-9141e3a85c2d] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] before_request: 87 : Request-Start] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 18:43:13,531] [INFO] [6d0abcd8-0b1c-4ec5-a165-9141e3a85c2d] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] teardown_request: 91 : Request-End] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 18:43:31,600] [INFO] [9afe3002-2655-4335-b6dd-6ae7bcc64bea] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] before_request: 87 : Request-Start] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 18:43:39,746] [INFO] [9afe3002-2655-4335-b6dd-6ae7bcc64bea] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] teardown_request: 91 : Request-End] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 18:59:37,757] [INFO] [f3c70358-d027-4209-9049-c166909e1395] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] before_request: 87 : Request-Start] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 18:59:44,321] [INFO] [f3c70358-d027-4209-9049-c166909e1395] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] teardown_request: 91 : Request-End] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 19:07:42,527] [INFO] [3e3706f1-6925-4ad3-b6f3-d4b9a56e0eba] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] before_request: 87 : Request-Start] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 19:07:43,427] [ERROR] [3e3706f1-6925-4ad3-b6f3-d4b9a56e0eba] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/common/utils.py] log_exception: 159 : Got exception during processing: ] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 50, in initialize
    self.message.mail.login(current_app.config['USER'], current_app.config['PASSWORD'])
  File "/usr/lib/python3.7/imaplib.py", line 598, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/apis/email_parser.py", line 18, in get
    ExtractDataFromXlsxFileService)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 20, in __init__
    self.initialize()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 55, in initialize
    raise InvalidEmailData
app.common.exceptions.InvalidEmailData
[2020-01-20 19:07:43,434] [ERROR] [3e3706f1-6925-4ad3-b6f3-d4b9a56e0eba] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py] log_exception: 1891 : Exception on /api/email-parser [GET]] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 50, in initialize
    self.message.mail.login(current_app.config['USER'], current_app.config['PASSWORD'])
  File "/usr/lib/python3.7/imaplib.py", line 598, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/apis/email_parser.py", line 18, in get
    ExtractDataFromXlsxFileService)
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 20, in __init__
    self.initialize()
  File "/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/core/service/email_parser/email_parser.py", line 55, in initialize
    raise InvalidEmailData
app.common.exceptions.InvalidEmailData
[2020-01-20 19:07:43,435] [INFO] [3e3706f1-6925-4ad3-b6f3-d4b9a56e0eba] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] teardown_request: 91 : Request-End] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 19:08:16,006] [INFO] [68caabff-5a6e-420a-b24b-8b5c581a628b] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] before_request: 87 : Request-Start] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 19:08:18,315] [INFO] [68caabff-5a6e-420a-b24b-8b5c581a628b] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] teardown_request: 91 : Request-End] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 19:10:29,551] [INFO] [324d0206-bf64-4565-9526-4b99e000ebcb] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] before_request: 87 : Request-Start] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
[2020-01-20 19:10:31,834] [INFO] [324d0206-bf64-4565-9526-4b99e000ebcb] [GET] [/api/email-parser] [] [/home/mtech/Nikunj/Internship/Python/Tasks/thawe-marine-service/app/manage.py] teardown_request: 91 : Request-End] [::ffff:127.0.0.1] [-] [PostmanRuntime/7.20.1] 
